# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

In this notebook, you will find 30 exercises that are essential to practice and learn numpy. If you want to do further exploration, you can continue working on `02.Extra_Drill_numpy.ipynb`.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__,np.show_config())

openblas64__info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', 

#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
B = np.zeros(10)
print(B)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [7]:
print(B.size)

10


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [8]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [11]:
A = np.zeros(10)
A[4]=1
print(A)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [17]:
A = np.arange(10,50)
print(A)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [18]:
print(np.flip(A))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [16]:
A = np.arange(0,9)
A = A.reshape(3,3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [19]:
B = np.array([1, 2, 0, 0, 4, 0 ])
indices = np.where(B != 0)
print(indices)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [20]:
C = np.eye(3,3)
print(C)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [26]:
My_array = np.random.random((3,3,3))
print(My_array)

[[[0.85309885 0.3249988  0.95407221]
  [0.49744489 0.54242712 0.99982134]
  [0.4285498  0.54310685 0.39660315]]

 [[0.13613245 0.09121551 0.15980218]
  [0.62584968 0.44015642 0.63354804]
  [0.537975   0.18569315 0.08916845]]

 [[0.00331804 0.17536872 0.16645246]
  [0.56023005 0.19141593 0.54537335]
  [0.65070305 0.05447123 0.61429035]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [34]:
print(np.info(np.max))

 amax(a, axis=None, out=None, keepdims=<no value>, initial=<no value>,
      where=<no value>)

Return the maximum of an array or maximum along an axis.

Parameters
----------
a : array_like
    Input data.
axis : None or int or tuple of ints, optional
    Axis or axes along which to operate.  By default, flattened input is
    used.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, the maximum is selected over multiple axes,
    instead of a single axis or all the axes as before.
out : ndarray, optional
    Alternative output array in which to place the result.  Must
    be of the same shape and buffer length as the expected output.
    See :ref:`ufuncs-output-type` for more details.

keepdims : bool, optional
    If this is set to True, the axes which are reduced are left
    in the result as dimensions with size one. With this option,
    the result will broadcast correctly against the input array.

    If the default value is passed, then `keepdims` will not be
    pass

In [31]:
C = np.random.random((10,10))
print(f" The maximum value is: {C.max()} \n The minimum value is: {C.min()}")

 The maximum value is: 0.992806525245351 
 The minimum value is: 0.00216115225677016


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [37]:
My_array = np.random.random((30))
print(My_array)
print(f"The mean value is: {My_array.mean()}")

[0.19193567 0.88883325 0.65036768 0.33952211 0.77436007 0.96424123
 0.44309108 0.10115016 0.48804777 0.90762946 0.74575132 0.66042018
 0.66250092 0.3345829  0.77209132 0.04354398 0.06208203 0.64536802
 0.73818409 0.58249212 0.13815722 0.42737066 0.40864289 0.82807941
 0.14334997 0.39605248 0.55017245 0.06849604 0.83961802 0.14230665]
The mean value is: 0.4979480377678438


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [52]:
My_array = np.ones((4,4))
# print(X)
My_array[1:-1,1:-1] = 0
print(My_array)




[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [53]:
print(f"The existing array is: \n {My_array}")
My_array = np.pad(My_array, pad_width= 1, mode= "constant", constant_values= 0)
print(f"The new array is: \n {My_array}")

The existing array is: 
 [[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]
The new array is: 
 [[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [66]:
print(np.info(np.nan))
x= 0* np.nan
print(f"0 * np.nan -->  {x}")
x = np.nan == np.nan
print(f"np.nan == np.nan -->  {x}")
x = np.inf > np.nan
print(np.inf)
print(f"np.inf > np.nan -->  {x}")
x = np.nan - np.nan
print(f"np.nan - np.nan -->  {x}")

print(f"np.nan in set([np.nan]) -->  {np.nan in set([np.nan])}")

print(f"0.3 == 3 * 0.1 -->  {0.3 == 3 * 0.1}")


Convert a string or number to a floating point number, if possible.
None
0 * np.nan -->  nan
np.nan == np.nan -->  False
inf
np.inf > np.nan -->  False
np.nan - np.nan -->  nan
np.nan in set([np.nan]) -->  True
0.3 == 3 * 0.1 -->  False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [67]:
X = np.diag([1,2,3,4],-1)
print(X)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [80]:
A = np.zeros((8,8))
A[1::2,::2]= 1
A[::2,1::2]=1
# A[::2,1::2]= 1
print(A)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [108]:
X = np.random.random((6,7,8))

print(X.shape)
print(X.size)
print(X[2][6][4])
print(X[1][5][4])



#np.info(np.unravel_index)
print(np.unravel_index(100,(6,7,8)))
print(np.ravel_multi_index((1,5,4), (6,7,8)))


#print(np.where[X[100]])

(6, 7, 8)
336
0.7890806629656109
0.041698030918153495
(1, 5, 4)
100


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [134]:
#print(np.info(np.tile))
#n = 8
# arr = np.zeros((8,8))
# print(arr)
np.tile(np.array([[0, 1], [1, 0]]), (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [141]:
A = np.random.random((5,5))
print(A)
Amin = A.min()
Amax = A.max()
print(Amin)
print(Amax)
x = A-Amin
y = Amax-Amin
print(x/y)


[[0.15330099 0.03896485 0.60800152 0.13902719 0.03380493]
 [0.98697698 0.1963141  0.47147014 0.3740278  0.4709244 ]
 [0.64052102 0.38728896 0.18953034 0.38285108 0.07299672]
 [0.47630816 0.09924821 0.49098386 0.13663346 0.33804989]
 [0.83216594 0.42417864 0.64274699 0.39983048 0.75324617]]
0.033804929396661576
0.9869769761187865
[[0.12536673 0.00541342 0.60240604 0.11039167 0.        ]
 [1.         0.17049301 0.45916706 0.35693752 0.45859452]
 [0.63652317 0.37085018 0.16337598 0.36619428 0.04111723]
 [0.46424277 0.06865841 0.47963946 0.10788034 0.31919207]
 [0.83758332 0.4095522  0.6388585  0.38400785 0.75478634]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [144]:
color = np.dtype([("r", np.ubyte, 1),  # np.dtype is used to creat the data type object.
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


C:\Users\user\AppData\Local\Temp\ipykernel_4872\845989871.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [152]:
A = np.arange(15).reshape(5,3)
print(A)
B = np.arange(6).reshape(3,2)
print('\n', B)
print(f"The result of A * B = \n {np.dot(A,B)}")

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

 [[0 1]
 [2 3]
 [4 5]]
The result of A * B = 
 [[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [155]:
x = np.arange(11)
x[3:9] *= -1

print(x)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [158]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))




10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [168]:
z = np.arange(5)
print(z)
print(z**z)
print(2 << z >> 2)
z <- z
1j * z
z/1/1
z<z>z


[0 1 2 3 4]
[  1   1   4  27 256]
[0 1 2 4 8]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [169]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)


C:\Users\user\AppData\Local\Temp\ipykernel_4872\1729466501.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
C:\Users\user\AppData\Local\Temp\ipykernel_4872\1729466501.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [171]:
x = np.random.uniform(-5, +5, 5)
np.copysign(np.ceil(np.abs(x)), x)

array([-1., -2., -4., -2., -1.])

#### 30. How to find common values between two arrays? (★☆☆)

In [175]:
a = np.arange(6).reshape(2,3)
b = np.arange(12).reshape(3,4)
np.intersect1d(a,b)

array([0, 1, 2, 3, 4, 5])